#ifndef OS_CONFIG_H
#define OS_CONFIG_H

// #define OS_LOG_QUEUE_ENABLE
// #define OS_TICK_LIST_MONITOR_ENABLE

#define OS_LOG_MAIN_BUFFER_SIZE (0U)
#define OS_LOG_USER_LOGS_NUM    (0U)

#define CONFIG_OS_TIME_DEPENDENT_TASKS_NUM  (37U)
#define CONFIG_OS_SYSTEM_TASKS_NUM          (1U)
#define CONFIG_OS_EVENT_DEPENDENT_TASKS_NUM (1U)
#define CONFIG_OS_RUN_TIME_USER_HOOKS_NUM   (1U)

#define OS_TICK_PERIOD_MS (5U)

#define OS_MEASUREMENT_NONE                (0U)
#define OS_MEASUREMENT_TICK_JITTER         (1U)
#define OS_MEASUREMENT_TASK_EXECUTION_TIME (2U)

#define OS_MEASUREMENT       (OS_MEASUREMENT_NONE)
#define OS_MESUREMENTS_TIMER (MCAL_TIMER_2)

#define OS_HYPERPERIOD_TICKS (200U)

typedef enum os_int_table
{
    SYSTICK_HANDLER,
    INTRX1_HANDLER,
    INTRX2_HANDLER,
    INTRX3_HANDLER,
    EXTINT1_HANDLER,
    TM7_OVFHANDLER,
    INT_NUM
} os_int_table_t;

#endif
