#ifndef APP_BUZZER_H
#define APP_BUZZER_H

#include "def.h"

#include "handlers/output/inc/handler_buzzer.h"

typedef handler_buzzer_toneSelection_t app_buzzer_tone_t;
#define APP_BUZZER_TONE_STARTUP            HANDLER_BUZZER_START_UP_TONE
#define APP_BUZZER_TONE_SHUTDOWN           HANDLER_BUZZER_SHUTDOWN_TONE
#define APP_BUZZER_TONE_VALID_KEY          HANDLER_BUZZER_KEY_VALID_PRESS_TONE
#define APP_BUZZER_TONE_INVALID_KEY        HANDLER_BUZZER_KEY_INVALID_PRESS_TONE
#define APP_BUZZER_TONE_CHILDLOCK_ACTIVE   HANDLER_BUZZER_CHILD_LOCK_ACTIVE_TONE
#define APP_BUZZER_TONE_CHILDLOCK_INACTIVE HANDLER_BUZZER_CHILD_LOCK_INACTIVE_TONE
#define APP_BUZZER_TONE_START              HANDLER_BUZZER_CYCLE_START_TONE
#define APP_BUZZER_TONE_PAUSE              HANDLER_BUZZER_CYCLE_PAUSE_TONE
#define APP_BUZZER_TONE_FINISH             HANDLER_BUZZER_CYCLE_FINISH_TONE
#define APP_BUZZER_TONE_FAULT              HANDLER_BUZZER_FAULT_TONE
#define APP_BUZZER_TONE_UNBALANCE          HANDLER_BUZZER_UNBALANCE_TONE

void app_buzzer_tone_set(app_buzzer_tone_t tone);

#endif
