#ifndef APP_NM_LOG_H
#define APP_NM_LOG_H

#include "def.h"

#include "app_user_interface.h"

typedef enum app_nm_log_cycleRecord
{
    APP_NORMAL_MODE_LOG_COURSE_CYCLE_NUM_START,
    APP_NORMAL_MODE_LOG_COURSE_CYCLE_NUM_END = APP_NORMAL_MODE_LOG_COURSE_CYCLE_NUM_START + APP_NORMAL_MODE_UI_COURSE_NUM - 1,

    APP_NORMAL_MODE_LOG_CYCLE_RECORD_LENGTH
} app_nm_log_cycleRecord_t;

typedef enum app_nm_log_error
{
    // common
    APP_NORMAL_MODE_LOG_ERROR_NO_ERROR = 0,
    APP_NORMAL_MODE_LOG_ERROR_DRAIN_FAILURE,                       // E1
    APP_NORMAL_MODE_LOG_ERROR_DRAIN_FILTER_FAILURE,                // E1-1
    APP_NORMAL_MODE_LOG_ERROR_LID_OPENING_FAILURE,                 // E2
    APP_NORMAL_MODE_LOG_ERROR_LID_LOCK_FAILURE,                    // E2-1
    APP_NORMAL_MODE_LOG_ERROR_MEMS_SENSOR_FAILURE,                 // E3
    APP_NORMAL_MODE_LOG_ERROR_DRAIN_VALVE_MOTOR_FAILURE,           // E4
    APP_NORMAL_MODE_LOG_ERROR_ABNORMAL_WATER_LEVEL_SENSOR_VALUE,   // E5-1
    APP_NORMAL_MODE_LOG_ERROR_MOTOR_CW_ROTATION,                   // E7-1
    APP_NORMAL_MODE_LOG_ERROR_MOTOR_CCW_ROTATION,                  // E7-2
    APP_NORMAL_MODE_LOG_ERROR_MOTOR_SPIN_ROTATION,                 // E7-3
    APP_NORMAL_MODE_LOG_ERROR_MOTOR_CW_CCW_ROTATION,               // E7-4
    APP_NORMAL_MODE_LOG_ERROR_MOTOR_FAILURE,                       // Ed-1
    APP_NORMAL_MODE_LOG_ERROR_DRIVER_IPM_FAILRUE,                  // Ed-2
    APP_NORMAL_MODE_LOG_ERROR_MOTOR_VOLTAGE_FAILURE,               // Ed-3
    APP_NORMAL_MODE_LOG_ERROR_DRIVER_NO_COMMUNICATION,             // Ed-C
    APP_NORMAL_MODE_LOG_ERROR_CRC_MISMATCH_FAILURE,                // ECRC
    APP_NORMAL_MODE_LOG_ERROR_ABNORMAL_WATER_WHEN_DRY,             // EA
    APP_NORMAL_MODE_LOG_ERROR_DISPLAY_DISCONNECTED_FAILURE,        // Ep
    APP_NORMAL_MODE_LOG_ERROR_LOW_POWER_FAILURE,                   // ELP
    APP_NORMAL_MODE_LOG_ERROR_ABNORMAL_THERMISTOR_VALUE,           // Et
    APP_NORMAL_MODE_LOG_ERROR_LINT_FILTER_FAILURE,                 // EU-1
    APP_NORMAL_MODE_LOG_ERROR_OVER_LOADING_FAILURE,                // EU-2

    // wash
    APP_NORMAL_MODE_WASH_LOG_ERROR_WATER_SUPPLY_FAILURE,              // E5
    APP_NORMAL_MODE_WASH_LOG_ERROR_UNBALANCE_FAILURE,                 // E3-2
    APP_NORMAL_MODE_WASH_LOG_ERROR_ABNORMAL_WATER_SUPPLY_OVERFLOW,    // E6-1
    APP_NORMAL_MODE_WASH_LOG_ERROR_WATER_SUPPLY_CONNECTION_FAILURE,   // EH
    APP_NORMAL_MODE_WASH_LOG_ERROR_ABNORMAL_WATER_LEAKAGE,            // E9
    APP_NORMAL_MODE_WASH_LOG_ERROR_FILL_HIGH_TEMP_FAILURE,            // EF-1

    // dry
    APP_NORMAL_MODE_DRY_LOG_ERROR_BLOWER_NOT_OPERATING_FAILURE,         // EU-2
    APP_NORMAL_MODE_DRY_LOG_ERROR_BLOWER_OFF_HEATER_ON_FAILURE,         // EU-3
    APP_NORMAL_MODE_DRY_LOG_ERROR_HEATER_OVERCURRENT_FAILURE,           // EU-4
    APP_NORMAL_MODE_DRY_LOG_ERROR_HEATER_NOT_OPERATING_FAILURE,         // EU-5
    APP_NORMAL_MODE_DRY_LOG_ERROR_HEATER_SHOULDNOT_OPERATING_FAILURE,   // EU-6
    APP_NORMAL_MODE_DRY_LOG_ERROR_HEATER_TEMP_SENSOR_FAILURE,           // EU-7
    APP_NORMAL_MODE_DRY_LOG_ERROR_LINT_FILTER_NOT_FOUND_FAILURE,        // EU-8

    APP_NORMAL_MODE_LOG_ERRORS_TOTAL_NUM,

    APP_NORMAL_MODE_LOG_TOTAL_NUM = APP_NORMAL_MODE_LOG_ERRORS_TOTAL_NUM + APP_NORMAL_MODE_LOG_CYCLE_RECORD_LENGTH
} app_nm_log_error_t;

#define APP_NORMAL_MODE_LOG_COURSE_ADDR_OFFSET (APP_NORMAL_MODE_LOG_ERRORS_TOTAL_NUM)

void app_nm_log_error_set(app_nm_log_error_t errorName);
void app_nm_log_completedCycleCount_set(app_nm_userInterface_courseSelection_t course);

app_nm_log_error_t app_nm_log_error_get(void);
uint16_t app_nm_log_errorCount_get(app_nm_log_error_t errorName);
uint16_t app_nm_log_completedCycleCount_get(app_nm_userInterface_courseSelection_t course);

void app_nm_log_errorCnt_clear(void);
void app_nm_log_courseCnt_clear(void);

#endif
